export const POST_REQUEST_START = "POST_REQUEST_START";
export const POST_SUCCESS_DATA = "POST_SUCCESS_DATA";
export const POST_FAILURE_DATA = "POST_FAILURE_DATA";
export const ADD_HISTORY = "ADD_HISTORY";
